CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    price DECIMAL(10,2) NOT NULL,
    stock_qty INT NOT NULL,
    category VARCHAR(80),
    image_url VARCHAR(500),
    seller_id BIGINT
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    total DECIMAL(10,2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL
);

INSERT INTO products (name, description, price, stock_qty, category, image_url)
SELECT 'Wireless Mouse', 'Ergonomic USB wireless mouse', 599.00, 25, 'Electronics', 'mouse.jpg'
WHERE NOT EXISTS (SELECT 1 FROM products WHERE name='Wireless Mouse');

INSERT INTO products (name, description, price, stock_qty, category, image_url)
SELECT 'Notebook', 'A5 ruled notebook', 120.00, 40, 'Stationery', 'notebook.jpg'
WHERE NOT EXISTS (SELECT 1 FROM products WHERE name='Notebook');

INSERT INTO products (name, description, price, stock_qty, category, image_url)
SELECT 'Water Bottle', 'Reusable 1 litre bottle', 399.00, 20, 'Lifestyle', 'bottle.jpg'
WHERE NOT EXISTS (SELECT 1 FROM products WHERE name='Water Bottle');
